language: node_js

node_js:
  - 'stable'

install:
  - npm install
  - mkdir -p build

script:
  - npm run build
  - npm run test
after_success:
  - npm install -g codecov
  - ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && codecov
